### ISSUE TITLE
need a bachelors of art student to make a description

### ISSUE THREAD

**Issue by chrisngyn** [chrisngyn/york-cs-primer#1]
under curriculum, under 1st year courses, I have a "foundational science requirement" which is meant for bachelors of science students (like me) but I know that bachelors of art students have a different requirement, something involving NATS courses?

a course description for that would be useful

**Comment by JamilleN** [comment]
I have 5 "General Education/Electives" course on top of my major courses. 

General Education means: 21 credits chosen from **humanities, natural science and social science courses**, with the constraint that at least 6.00 credits must be chosen from each of humanities, social science and natural science areas.

Electives means: All BA degree candidates must choose at least 18 elective credits outside the major. **These credits may not be part of the general education** or any other named requirements (such as MATH requirements). Honours double major and major/minor programs automatically meet this regulation. It is recommended that students in the Honours Major, Honours Double Major or Honours Major/Minor programs, where computer science is the major, take a linear algebra course such as SC/MATH 1025 3.00 among their electives. Additional elective credits, as required, for an overall total of 120 credits.

**Comment by chrisngyn** [comment]
thanks for the description, making the change + closing this issue!
